sudo: enabled
addons:
  chrome: stable

language: php

services:
  - mysql

deploy:
  skip-cleanup: false
  github-token: $GITHUB_TOKEN

env:
  global:
    - CODE_COVERAGE=false
    - DB=mysql
    - DB_NAME="magento_travis"
    - PHPUNIT_ENVIRONMENT=true
    - TEST_ENV=sandbox
    - HOST_NAME="http://travis_magento.loc/"

matrix:
  include:
    - php: 5.5
      env: PHPUNIT_PHAR=tests/unit/phpunit-4.8.36.phar MAGENTO_VERSION=magento-mirror-1.8.1.0
    - php: 5.5
      env: PHPUNIT_PHAR=tests/unit/phpunit-4.8.36.phar MAGENTO_VERSION=magento-mirror-1.9.3.6
    - php: 5.6
      env: PHPUNIT_PHAR=tests/unit/phpunit-5.7.9.phar MAGENTO_VERSION=magento-mirror-1.8.1.0
    - php: 5.6
      env: PHPUNIT_PHAR=tests/unit/phpunit-5.7.9.phar MAGENTO_VERSION=magento-mirror-1.9.3.6

before_install:
  - mysql -e 'DROP DATABASE IF EXISTS `$DB_NAME`;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `$DB_NAME`;'

before_script:
  - composer self-update -q
  - if [ -n "$GITHUB_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_TOKEN}; fi;
  - if [ -n "INTEGRATION_TESTS_TOKEN" ]; then composer config github-oauth.github.com ${INTEGRATION_TESTS_TOKEN}; fi;
  - composer show -i
  - bash /home/travis/build/BoltApp/bolt-magento1/tests/scripts/apache_setup.sh
  - bash /home/travis/build/BoltApp/bolt-magento1/tests/scripts/magento_install.sh

script:
  - cd /home/travis/build/BoltApp/bolt-magento1/
  - export PHPUNIT_ENVIRONMENT=$PHPUNIT_ENVIRONMENT
  - php ${PHPUNIT_PHAR} -c tests/unit/phpunit.xml
#   Integration tests TODO remove single branch and run from master
  - php /home/travis/build/BoltApp/bolt-magento1/tests/scripts/create_discounts.php
  - php /home/travis/build/BoltApp/bolt-magento1/tests/scripts/create_products.php
  - git clone --single-branch -b ak-magento1-admin-test https://${INTEGRATION_TESTS_TOKEN}@github.com/BoltApp/integration-tests.git/
  - cd integration-tests
  - npm install
  - xvfb-run npm run test-magento1
